version: "3.7"
services:
  frontend-app:
    build:
      context: ./frontend
    command: npm start
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
        - backendhost=backend-app
        - WDS_SOCKET_HOST=127.0.0.1 
        - CHOKIDAR_USEPOLLING=true
        - WATCHPACK_POLLING=true                   
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
          mongohost: mongodb-app     
  mongodb-app:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
          MONGO_INITDB_DATABASE: mydb
volumes:
  mongodata: