conn = new Mongo();
db = conn.getDB("mydb");


db.getCollection("glossary").insert({name:"Ett namn",description:"En beskrivning"});
db.getCollection("glossary").insert({name:"två",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"tre",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"fyra",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"5",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"6",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"8n",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"9mn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 34 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 12 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 34 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2134 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2134 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2134 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2341 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 1234 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett an1234nat namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2134",description:"En beskrivning"});
db.getCollection("glossary").insert({name:"Ett 4231 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2314 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2314 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2134 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2134 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 4231 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2413 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 56 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2245 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 6524 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 625 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 3462 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 2346 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 876 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 655 namn",description:"En annan beskrivning"});
db.getCollection("glossary").insert({name:"Ett 768 namn",description:"En annan beskrivning"});